### ISSUE TITLE
Add indications on how to run Jupyter notebooks with Docker in a few minutes

### ISSUE THREAD

**Issue by denisarnaud** [tirthajyoti/PythonMachineLearning#3]
The https://github.com/machine-learning-helpers/docker-python-jupyter project builds a Docker image so that the (your) Jupyter notebooks can be run out-of-the-box on almost any platform in a few minutes.

It gives something like:
* Initialization of the Git repository for the Jupyter notebooks:
```bash
$ mkdir -p ~/dev/ml
$ cd ~/dev/ml
$ git clone https://github.com/tirthajyoti/PythonMachineLearning.git
```
* Initialization of the Docker image to run those Jupyter notebooks:
```bash
$ docker pull artificialintelligence/python-jupyter
```
* Usage:
```bash
$ cd ~/dev/ml/PythonMachineLearning
$ docker run -d -p 9000:8888 -v ${PWD}:/notebook -v ${PWD}:/data artificialintelligence/python-jupyter
```
And then you can open http://localhost:9000 in your browser.

Any modification to the notebooks may be committed to the [Git repository](https://github.com/tirthajyoti/PythonMachineLearning) (if you are registered as a contributor), and/or submitted as a [pull request](http://github.com/tirthajyoti/PythonMachineLearning/pulls).

* Shutdown the Docker image
```bash
$ docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                    NAMES
431b12a93ccf        artificialintelligence/python-jupyter   "/bin/sh -c 'jupyt..."   4 minutes ago       Up 4 minutes        0.0.0.0:9000->8888/tcp   friendly_euclid
$ docker kill 431b12a93ccf 
```

So, all the above could be added to your [README.md file](http://github.com/tirthajyoti/PythonMachineLearning/blob/master/README.md).

**Comment by tirthajyoti** [comment]
Done! Thanks!

**Comment by denisarnaud** [comment]
Great, thanks for your valuable work!
